import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar/Navbar";
import Footer from "./_components/Footer/Footer";
import { Toaster } from 'react-hot-toast';
import NextAuthprovider from "./providers/nextauthProvider";
import Providers from "./providers/react-query-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FreshCart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <NextAuthprovider>
            <Toaster position="top-right"/>
            <Navbar />
            <main className="bg-gray-50 min-h-[calc(100vh-4.5rem)] ">
              {children}
            </main>
            <Footer />
          </NextAuthprovider>
        </Providers>
      </body>
    </html>
  );
}
//px-4 md:px-10 xl:px-4